services:
  frontend:
    image: blog-front
    build: osa5/bloglist-frontend/
    restart: unless-stopped

  backend:
    image: blog-back
    build: osa4/blogilista/
    environment:
      - DB_HOST=mongo
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7.0-rc
    volumes:
      - ./osa4/blogilista/mongo_data:/data/db
    restart: unless-stopped

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./bloglist.nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

