version: '3.8'

services:
  puhelinluettelo:
    image: tomjtoth/puhelinluettelo
    build:
      dockerfile: puhelinluettelo.Dockerfile
    environment:
      - DB_HOST=${MONGO_HOST}
    networks:
      nginx:

  mongo:
    image: mongo:7.0-rc
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:

networks:
  nginx:
    # this actually exists on my VPS
    external: true
