### create new
POST http://localhost:3001/api/blogs
content-type: application/json

{
    "title": "abc",
    "author": "xyz",
    "url": "www",
    "likes": 10
}

### missing 1/4 fields should fail with 400
POST http://localhost:3001/api/blogs
content-type: application/json

{
    "author": "xyz",
    "url": "www",
    "likes": 10
}

### missing 1/4 fields should fail with 400
POST http://localhost:3001/api/blogs
content-type: application/json

{
    "title": "abc",
    "url": "www",
    "likes": 10
}

### missing 1/4 fields should fail with 400
POST http://localhost:3001/api/blogs
content-type: application/json

{
    "title": "abc",
    "author": "xyz",
    "likes": 10
}

### missing "likes" fields should succeed with 201
POST http://localhost:3001/api/blogs
content-type: application/json

{
    "title": "abc",
    "author": "xyz",
    "url": "www"
}

### create user
POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "aaa",
    "name": "Aa A",
    "password": "aaa"
}
